# Generated by Django 4.0.2 on 2022-03-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='category',
            field=models.CharField(blank=True, choices=[('OPINION', 'OPINION'), ('FUTURE_PREDICTION', 'FUTURE_PREDICTION'), ('IMPOSSIBLE', 'IMPOSSIBLE'), ('UNINTERESTING', 'UNINTERESTING'), ('NEEDS_CONTEXT', 'NEEDS_CONTEXT')], max_length=255),
        ),
    ]
